version: 2

sources:
  - name: nfl_data  # Change this from 'raw_nfl'
    description: "Raw NFL data from APIs"
    tables:
      - name: games
        description: "Raw NFL games data"
        columns:
          - name: game_id
            description: "Unique game identifier"
            tests:
              - unique
              - not_null
      - name: player_stats
        description: "Raw NFL player statistics"
        columns:
          - name: player_id
            description: "Unique player identifier"
            tests:
              - not_null
      - name: pbp_data
        description: "Play by play data"
        columns:
          - name: play_id
            description: "Unique play identifier"
            tests:
              - not_null
      - name: rosters
        description: "NFL rosters by season"
        columns:
          - name: player_id
            description: "Unique player identifier"
            tests:
              - not_null
      - name: ngs_data
        description: "AWS Next Gen Stats data"
      - name: schedule_2025
        description: "2025 NFL schedule data"
        columns:
          - name: game_id
            tests: [unique, not_null]
      - name: pbp_data_2025
        description: "2025 live play-by-play data"
        columns:
          - name: game_id
            tests: [not_null]
      - name: player_stats_2025
        description: "2025 live player statistics"
        columns:
          - name: player_id
            tests: [not_null]
      - name: rosters_2025
        description: "2025 NFL rosters"
        columns:
          - name: player_id
            tests: [not_null]