version: 2

models:
  # ============================================
  # CORE ML MODELS
  # ============================================

  - name: team_performance
    description: "Comprehensive team performance model with rolling averages, trends, and efficiency metrics"
    columns:
      - name: team
        description: "Team abbreviation (e.g., KC, BUF)"
        tests:
          - not_null

      - name: season
        description: "NFL season year"
        tests:
          - not_null

      - name: week
        description: "Week number in season"
        tests:
          - not_null

      - name: game_id
        description: "Unique identifier for each game"
        tests:
          - not_null

      - name: total_epa
        description: "Expected Points Added for the game"
        tests:
          - not_null

      - name: recent_form
        description: "Team form indicator"
        tests:
          - accepted_values:
              arguments:
                values: ['hot', 'cold', 'average']

  - name: team_game_features
    description: "Base team game-level statistics from play-by-play data"
    columns:
      - name: game_id
        tests: [not_null]
      - name: team
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: week
        tests: [not_null]
      - name: total_yards
        tests: [not_null]
      - name: total_epa
        tests: [not_null]
      - name: total_turnovers
        tests: [not_null]

  - name: game_labels
    description: "Game results and labels for ML training"
    columns:
      - name: game_id
        description: "Unique identifier for each game"
        tests:
          - not_null
          - unique

      - name: season
        tests: [not_null]

      - name: week
        tests: [not_null]

      - name: home_team
        tests: [not_null]

      - name: away_team
        tests: [not_null]

      - name: home_score
        description: "Home team final score"
        tests: [not_null]

      - name: away_score
        description: "Away team final score"
        tests: [not_null]

  - name: game_training_dataset
    description: "ML-ready dataset with team features and game outcomes"
    columns:
      - name: game_id
        tests: [not_null, unique]

      - name: home_team
        tests: [not_null]

      - name: away_team
        tests: [not_null]

      - name: home_win
        description: "1 if home team won, 0 if away team won, null for ties"

      - name: home_avg_epa_l3
        description: "Home team 3-game rolling average EPA"

      - name: away_avg_epa_l3
        description: "Away team 3-game rolling average EPA"

  # ============================================
  # ANALYTICS MODELS
  # ============================================

  - name: team_dashboard
    description: "Analytics-friendly team performance view for BI tools"
    columns:
      - name: team
        tests: [not_null]
      - name: season
        tests: [not_null]
      - name: week
        tests: [not_null]
      - name: performance_quartile
        description: "Performance quartile ranking"
        tests:
          - accepted_values:
              arguments:
                values: ['Top 25%', 'Top 50%', 'Bottom 50%', 'Bottom 25%']
      - name: season_phase
        description: "Phase of NFL season"
        tests:
          - accepted_values:
              arguments:
                values: ['Early Season', 'Mid Season', 'Late Season']

  # ============================================
  # PLAYER MODELS
  # ============================================

  - name: player_season
    description: "Basic player season-level statistics"
    columns:
      - name: player_id
        tests: [not_null]
      - name: season
        tests: [not_null]

  - name: player_season_ngs
    description: "Player season stats enhanced with Next Gen Stats data"
    columns:
      - name: player_id
        tests: [not_null]
      - name: season
        tests: [not_null]